### PR TITLE
make 'review' command optional

### PR DESCRIPTION
**Pull request by kovetskiy**

### CODE REVIEW

**Comment by seletskiy** [comment]
`reviewMode` function need to be changed too, because it will not work.

**Comment by seletskiy** [comment]
@kovetskiy ping

**Comment by kovetskiy** [comment]
oh, I missed your comment, I'll fix it later.

**Comment by kovetskiy** [comment]
@seletskiy I fixed this, also I moved `inbox` usage as first item for preventing docopt parsing `<project>/<repo>/<pr>` as `inbox`.

**Comment by kovetskiy** [comment]
@seletskiy ping

**Pull request merged**
